services:
  spark-master:
    build: 
      context: .
      dockerfile: master/Dockerfile
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./conf/spark-env.sh:/opt/spark/conf/spark-env.sh

  spark-worker:
    build: 
      context: .
      dockerfile: worker/Dockerfile
    container_name: spark-worker
    ports:
      - "7078:7078"
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
    volumes:
      - ./conf/spark-env.sh:/opt/spark/conf/spark-env.sh


