services:
  spark-master:
    build: 
      context: .
      dockerfile: master/Dockerfile
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
    environment:
      - "SPARK_MODE=master"

  spark-worker:
    build: 
      context: .
      dockerfile: worker/Dockerfile
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://192.168.0.32:7077 


