services:
  spark-master:
    build: 
      context: .
      dockerfile: master/Dockerfile
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
    environment:
      - "SPARK_MASTER_HOST=spark-master"
    volumes:
      - ./app:/app
      - ./data:/data
    networks:
      - spark-net

  spark-worker:
    build: 
      context: .
      dockerfile: worker/Dockerfile
    container_name: spark-worker
    environment:
      - "SPARK_MASTER_URL=spark://192.168.0.32:7077"
      - "SPARK_WORKER_MEMORY=2g"
      - "SPARK_WORKER_CORES=2"
    volumes:
      - ./app:/app
    networks:
      - spark-net

networks:
  spark-net:

