services:
  spark-master:
    build: 
      context: .
      dockerfile: master/Dockerfile
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MODE=master

  spark-worker:
    build: 
      context: .
      dockerfile: worker/Dockerfile
    container_name: spark-worker
    ports:
      - "7078:7078"
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://192.168.0.32:7077


